Django/Dproject/advCBV/advCBV/urls.py
from django.contrib import admin
from django.urls import path,re_path,include
from basic_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^$',views.IndexView.as_view()),
    re_path(r'^basic_app/',include('basic_app.urls',namespace='basic_app')),
]

Django/Dproject/advCBV/basic_app/urls.py
from django.urls import path,re_path
from basic_app import views



app_name= 'basic_app'

urlpatterns= [

re_path(r'^$',views.SchoolListView.as_view(),name='list'),

#re_path(r'^(?P<pk>[-\w]+)/$',views.SchoolDetailView.as_view(),name='detail')
re_path(r'^(?P<pk>\d+)/$',views.SchoolDetailView.as_view(),name='detail'),
re_path(r'^create/',views.SchoolCreateView.as_view(),name='create'),
re_path(r'^update/(?P<pk>\d+)/$',views.SchoolUpdateView.as_view(),name='update'),
re_path(r'^delete/(?P<pk>\d+)/$',views.SchoolDeleteView.as_view(),name='delete'),

]

Django/Dproject/advCBV/basic_app/models.py
from django.db import models
#from django.core.urlresolvers import reverse
from django.urls import reverse

# Create your models here.

class School(models.Model):

	name=models.CharField(max_length=256)
	principal=models.CharField(max_length=256)
	city=models.CharField(max_length=256)


	def __str__(self):

		return self.name


	def get_absolute_url(self):

		return reverse("basic_app:detail",kwargs={'pk':self.pk})
		


class Student(models.Model):

	name=models.CharField(max_length=256)
	age=models.PositiveIntegerField()
	school=models.ForeignKey(School,related_name='students',on_delete=models.CASCADE)


	def __str__(self):
		
		return self.name

Django/Dproject/advCBV/basic_app/views.py
from django.shortcuts import render
from django.views.generic import (View,TemplateView,ListView,DetailView,
								  CreateView,UpdateView,DeleteView)

from django.urls import reverse_lazy
from django.http import HttpResponse
from basic_app import models

# Create your views here.


class SchoolListView(ListView):

	context_object_name='schools'

	# {% for school in school_list %} in ListView itself generated school_list variable but for better practice we declare variable for user perpose-->

	model=models.School



class SchoolDetailView(DetailView):

	context_object_name='school_detail'

	model=models.School

	template_name='basic_app/school_detail.html'


class SchoolCreateView(CreateView):

	fields=('name','principal','city')

	model=models.School



class SchoolUpdateView(UpdateView):

	fields=('name','principal')

	model=models.School

class SchoolDeleteView(DeleteView):

	model=models.School

	success_url=reverse_lazy('basic_app:list')




















class IndexView(TemplateView):

	template_name="index.html"

	def get_context_data(self,**kwargs):

		context=super().get_context_data(**kwargs)
		context['injectme']='Basic Injections!'
		return context


# class CBView(View):

# 	def get(self,request):

# 		return HttpResponse(" CLASS BASED VIEW")




# def index(request):

# 	return render(request,'index.html')

Django/Dproject/advCBV/basic_app/templates/basic_app/basic_app_base.html
<!DOCTYPE html>
<html>
<head>
	<title>BASE</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

</head>
<body>

	<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="{% url 'basic_app:list' %}">School</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'admin:index' %}">Admin<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
      </li>

      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>




      </li>


      <li class="nav-item">
        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>
	<div class='container'>

		{% block body_block %}

		{% endblock%}
		
	</div>
	
</body>
</html>

Django/Dproject/advCBV/basic_app/templates/basic_app/school_confirm_delete.html
{% extends 'basic_app/basic_app_base.html' %}


{% block body_block %}

<h1>Delete {{school.name}}?</h1>


<form  method="POST" >

	{% csrf_token %}

	<input type="submit" clas="btn btn-danger" value="Delete">

	<a href="{% url 'basic_app:detail' pk=school.pk %}">Cancel</a>
	
	
</form>

{% endblock %}

Django/Dproject/advCBV/basic_app/templates/basic_app/school_detail.html
{% extends 'basic_app/basic_app_base.html'%}

{% block body_block %}

<div class="jumbotron">

	<h1>Welcome To School Details Page!</h1>
	<h2>School Details:</h2>

	<p>Name:{{school_detail.name}}</p>
	<p>Principal:{{school_detail.principal}}</p>
	<p>City:{{school_detail.city}}</p>
	<h3>Students:</h3>

	{% for student in school_detail.students.all %}

	<p>{{student.name}} who is {{student.age}} years old.</p>

	{% endfor %}
	
</div>
	<div class='container'>
	<p><a class="btn btn-warning" href="{% url 'basic_app:update' pk=school_detail.pk %}">Update</a> </p>
		
	</div>

{% endblock %}

Django/Dproject/advCBV/basic_app/templates/basic_app/school_form.html
{% extends 'basic_app/basic_app_base.html' %}


{% block body_block %}

<h1>
	{% if not form.instance.pk %}

		Create School

	{% else %}
	
	Update School

	{% endif %}	


</h1>

	<form  method="POST" accept-charset="utf-8">

		{% csrf_token%}
		{{form.as_p}}
		<input type="submit" class="btn btn-primary" value="Submit">
		

	</form>




{% endblock %}

Django/Dproject/advCBV/basic_app/templates/basic_app/school_list.html
{% extends 'basic_app/basic_app_base.html' %}


{% block body_block %}

<h1>Welcome to the List of All Schools!</h1>

	<ol>
		{% for school in schools %}

		 <h2><li><a href="{{school.id}}">{{school.name}}</a></li></h2>

		{% endfor %}
	
	</ol>

{% endblock %}
